In [1]:
import numpy as np  
import pandas as pd
import re

In [3]:
#Define a function to parse survey data 
def readDATFile(layout_file, dat_file):
    columns = []
    
    with open(layout_file, 'r') as file:
        for line in file:
           
            match = re.match(r'(\S+)\s+\S+\s+\S+\s+(\d+)\s+(\d+)', line)
            if match:
                col_name = match.group(1) 
                start_pos = int(match.group(2)) - 1  
                end_pos = int(match.group(3))  
                columns.append((col_name, start_pos, end_pos))
    colspecs = [(start, end) for _, start, end in columns]
    column_names = [name for name, _, _ in columns] 
    df = pd.read_fwf(dat_file, colspecs=colspecs, header=None, names=column_names) 
    return df 


survey2021 = readDATFile('DAT_DATA/pcg21Public/LAYOUTPCG21.TXT', 'DAT_DATA/pcg21Public/EPCG21.DAT')

In [4]:
#Test to check if scraping is correct
summary = survey2021[['OCEDRLP']].value_counts()
print(summary)

OCEDRLP
1          55324
2          21921
L          17284
3          11750
dtype: int64

In [5]:
survey2019 = readDATFile('DAT_DATA/pcg19Public/LAYOUTPCG19.TXT', 'DAT_DATA/pcg19Public/EPCG19.DAT')

In [6]:
survey2019

,ACADV,ACCAR,ACCCEP,ACCHG,ACDRG,ACEM,ACFPT,ACGRD,ACINT,ACLIC,...,WRKGP,WTRCHOC,WTREASN,WTREM,WTRLIC,WTROPPS,WTROT,WTRPERS,WTRSKL,WTSURVY
0,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,683.1451
1,N,N,Y,N,0,N,3,N,Y,N,...,N,N,1,N,Y,Y,N,Y,Y,64.5046
2,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,2139.9825
3,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,272.8289
4,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,N,N,N,N,N,Y,414.3448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92532,L,L,L,L,L,L,L,L,L,L,...,Y,N,6,N,N,N,N,Y,Y,425.1265
92533,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,237.9650
92534,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,22.1730
92535,N,N,N,N,3,Y,1,N,N,N,...,Y,N,1,N,N,Y,N,N,Y,149.5727
92536,L,L,L,L,L,L,L,L,L,L,...,Y,N,5,Y,N,N,N,N,N,195.9421

In [7]:
#Test to check if scraping is correct
summary = survey2019[['OCEDRLP']].value_counts()
print(summary)

OCEDRLP
1          48243
2          19389
L          14420
3          10485
dtype: int64

In [ ]:
survey2017 = readDATFile('DAT_DATA/pcg17Public/LAYOUTPCG17.TXT', 'DAT_DATA/pcg17Public/EPCG17.DAT')

In [ ]:
survey2017

In [ ]:
#Test to check if scraping is correct
summary = survey2017[['OCEDRLP']].value_counts()
print(summary)

In [ ]:
survey2021.to_csv("CSV_DATA/RawData/2021.csv")
survey2019.to_csv("CSV_DATA/RawData/2019.csv")
survey2017.to_csv("CSV_DATA/RawData/2017.csv")