In [24]:
import numpy as np  
import pandas as pd
import re

In [25]:
#Define a function to parse survey data 
def readDATFile(layout_file, dat_file):
    columns = []
    
    with open(layout_file, 'r') as file:
        for line in file:
           
            match = re.match(r'(\S+)\s+\S+\s+\S+\s+(\d+)\s+(\d+)', line)
            if match:
                col_name = match.group(1) 
                start_pos = int(match.group(2)) - 1  
                end_pos = int(match.group(3))  
                columns.append((col_name, start_pos, end_pos))
    colspecs = [(start, end) for _, start, end in columns]
    column_names = [name for name, _, _ in columns] 
    df = pd.read_fwf(dat_file, colspecs=colspecs, header=None, names=column_names) 
    return df 


survey2021 = readDATFile('pcg21Public/LAYOUTPCG21.TXT', 'pcg21Public/EPCG21.DAT')

In [26]:
#Test to check if scraping is correct
summary = survey2021[['OCEDRLP']].value_counts()
print(summary)

OCEDRLP
1          55324
2          21921
L          17284
3          11750
dtype: int64

In [2]:
survey2019 = readDATFile('DAT_DATA/pcg19Public/LAYOUTPCG19.TXT', 'DAT_DATA/pcg19Public/EPCG19.DAT')

In [3]:
survey2019

,ACADV,ACCAR,ACCCEP,ACCHG,ACDRG,ACEM,ACFPT,ACGRD,ACINT,ACLIC,...,WRKGP,WTRCHOC,WTREASN,WTREM,WTRLIC,WTROPPS,WTROT,WTRPERS,WTRSKL,WTSURVY
0,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,683.1451
1,N,N,Y,N,0,N,3,N,Y,N,...,N,N,1,N,Y,Y,N,Y,Y,64.5046
2,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,2139.9825
3,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,272.8289
4,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,N,N,N,N,N,Y,414.3448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92532,L,L,L,L,L,L,L,L,L,L,...,Y,N,6,N,N,N,N,Y,Y,425.1265
92533,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,237.9650
92534,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,22.1730
92535,N,N,N,N,3,Y,1,N,N,N,...,Y,N,1,N,N,Y,N,N,Y,149.5727
92536,L,L,L,L,L,L,L,L,L,L,...,Y,N,5,Y,N,N,N,N,N,195.9421

In [4]:
#Test to check if scraping is correct
summary = survey2019[['OCEDRLP']].value_counts()
print(summary)

OCEDRLP
1          48243
2          19389
L          14420
3          10485
dtype: int64

In [5]:
survey2017 = readDATFile('pcg17Public/LAYOUTPCG17.TXT', 'pcg17Public/EPCG17.DAT')

In [6]:
survey2017

,ACADV,ACCAR,ACCCEP,ACCHG,ACDRG,ACEM,ACFPT,ACGRD,ACINT,ACLIC,...,WRKGP,WTRCHOC,WTREASN,WTREM,WTRLIC,WTROPPS,WTROT,WTRPERS,WTRSKL,WTSURVY
0,L,L,L,L,L,L,L,L,L,L,...,Y,N,5,Y,Y,N,N,Y,Y,541.9612
1,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,Y,N,Y,N,N,Y,4801.3457
2,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,1426.4519
3,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,Y,N,N,N,N,Y,6375.9788
4,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,N,N,Y,N,Y,Y,3287.4800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83667,L,L,L,L,L,L,L,L,L,L,...,N,L,L,L,L,L,L,L,L,105.8457
83668,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,Y,N,Y,N,Y,Y,38.3931
83669,Y,N,N,N,2,N,2,Y,N,N,...,Y,N,1,Y,Y,N,N,Y,Y,39.2132
83670,L,L,L,L,L,L,L,L,L,L,...,Y,N,5,Y,N,N,N,N,Y,613.9644
83671,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,72.3658

In [7]:
#Test to check if scraping is correct
summary = survey2017[['OCEDRLP']].value_counts()
print(summary)

OCEDRLP
1          42968
2          17136
L          14041
3           9527
dtype: int64

In [55]:
survey2021.to_csv("CSV_DATA/RawData/2021.csv")
survey2019.to_csv("CSV_DATA/RawData/2019.csv")
survey2017.to_csv("CSV_DATA/RawData/20.csv")

,ACADV,ACCAR,ACCCEP,ACCHG,ACDRG,ACEM,ACFPT,ACGRD,ACINT,ACLIC,...,WRKGP,WTRCHOC,WTREASN,WTREM,WTRLIC,WTROPPS,WTROT,WTRPERS,WTRSKL,WTSURVY
0,L,L,L,L,L,L,L,L,L,L,...,Y,Y,5,Y,Y,Y,N,N,Y,1773.4187
1,L,L,L,L,L,L,L,L,L,L,...,Y,Y,1,N,Y,Y,N,N,Y,91.5643
2,L,L,L,L,L,L,L,L,L,L,...,Y,N,1,N,Y,N,N,Y,Y,943.7777
3,Y,Y,Y,N,2,N,2,N,Y,N,...,Y,N,1,N,N,N,N,N,Y,470.5196
4,L,L,L,L,L,L,L,L,L,L,...,Y,L,L,L,L,L,L,L,L,6173.4583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106273,L,L,L,L,L,L,L,L,L,L,...,N,L,L,L,L,L,L,L,L,68.8164
106274,N,Y,Y,N,3,N,1,Y,N,N,...,Y,N,1,N,Y,N,N,N,Y,98.2414
106275,L,L,L,L,L,L,L,L,L,L,...,N,L,L,L,L,L,L,L,L,469.0670
106276,L,L,L,L,L,L,L,L,L,L,...,Y,N,3,Y,Y,N,N,Y,Y,287.8653
106277,L,L,L,L,L,L,L,L,L,L,...,Y,N,2,Y,N,Y,N,Y,Y,334.4052